### PR TITLE
Updates to make links standard underline style for the entire app

### PR DESCRIPTION
**Pull request by line47**
Fixes https://github.com/18F/e-QIP-prototype/issues/185 

screen shot 2018-11-02 at 5 06 18 pm
screen shot 2018-11-02 at 5 06 28 pm
screen shot 2018-11-02 at 5 06 37 pm
screen shot 2018-11-02 at 5 07 25 pm

### CODE REVIEW

**Comment by line47** [comment]
Yeah I'm still having issues with viewing IE locally (long story), @christopherhuii if you wouldn't mind taking a look in IE11 that would be 💯

**Comment by christopherhuii** [comment]
I will review in IE11. Thanks

**Comment by christopherhuii** [comment]
Doing a first pass in Chrome:

When hovered, most fields apply the blue text color and solid underline.

In "Information about you" -> "Your identifying information", the "Remove comment" link is blue and underlined before the hover. When hovered, the text color turns to black and is still hovered.

screen shot 2018-11-07 at 9 09 28 am

**Comment by christopherhuii** [comment]
Similarly, in "Your history" -> "Where you went to school", have the underline by default, the text color is blue, and does not change on hover. It's probably also worth mentioning that the underline is black in this context.

**Comment by christopherhuii** [comment]
Are focus states around input fields still dashed?

If my previous comments are OK, then the PR is good to go. Once I get confirmation that my previous comments are intentional and as designed, I will approve.

**Comment by line47** [comment]
Thanks @christopherhuii - those are some additional issues to work through 👍

**Comment by line47** [comment]
@christopherhuii The links should be underlined by default (before hover and also when hovering)  they should have a dashed focus state. 

Seems like the only thing to fix is the black text on hover which I'm not seeing in Chrome on mac.

**Comment by christopherhuii** [comment]
@line47 Sorry, I should have been more clear. It goes from light blue to darker blue.

I wasn't sure if it's intentional because the accordions go from black to light blue. If this is all intentional, then it looks good. Everything is consistent from Chrome to IE11

**Pull request merged**
