### PR TITLE
Encapsulate alternate address behavior

### PR DESCRIPTION
**Pull request by el-mapache**
Completes #1107, #1108

* Should make it easier to reuse this functionality in the code
* Adds `AlternateAddress` to employment and the reference address section of the `History` subsection

### CODE REVIEW

**Comment by ryanhofdotgov** [comment]
@el-mapache Still poking it, but here is one data point:

If I add a self-employed entry, and enter an "Outside of the US" address for verifier, and then click "No" to following APO question, then:
* APO question disappears
* Address field set is cleared and set to "In the United States"

screen shot 2018-11-06 at 3 42 40 pm

**Comment by ryanhofdotgov** [comment]
Also:
* Same thing happens with unemployment. And also if you click "Yes" instead of "No" to APO question
* Can't enter in an APO address for primary verifier address – clicking on the APO/FPO button leaves (or resets) the address to the domestic field set.

But the residence verifier workflow looks good :+1:

**Comment by el-mapache** [comment]
Thanks, working on fixing now!

**Comment by el-mapache** [comment]
@ryanhofdotgov I think this should be good to go, thanks again for reviewing

**Comment by ryanhofdotgov** [comment]
I'm seeing an odd problem, but have split if off into https://github.com/18F/e-QIP-prototype/issues/1117

**Pull request merged**
