### PR TITLE
Fix phantom validation errors

### LINKED ISSUE #1254: Investigate phantom validation errors on complete scenario JSON files
For test 1-9.json, purge database, load up scenario file, ensure that entire form validates and is submit-able.

To test validation, I would go to each section review page, see validation errors there, then go to final page and validate.

### PR DESCRIPTION
**Pull request by hursey013**
Fixes #1254

Scenarios tested locally:
_Check overall validation, click into each section's review, and run final review_

- [x] Scenario 1
- [x] Scenario 2
- [x] Scenario 3
- [x] Scenario 4
- [x] Scenario 5
- [x] Scenario 6
- [x] Scenario 7
- [x] Scenario 8
- [x] Scenario 9

To test these fixes, you can load up the various test scenarios using the steps here: https://github.com/18F/e-QIP-prototype/blob/develop/docs/test-scenarios.md. To replicate the issues you can first load the scenarios using the `develop` branch, and then switch to this branch to see them resolved.

### CODE REVIEW

**Comment by hursey013** [comment]
I'm still working through an issue with addresses that I discovered after the fact, so moving this back to `WIP` for now.

**Comment by hursey013** [comment]
Ok, this is ready to go.

**Comment by ryanhofdotgov** [comment]
@hursey013 It looks like this PR also fixes https://github.com/18F/e-QIP-prototype/issues/1205?

**Comment by hursey013** [comment]
@ryanhofdotgov yes, this will resolve #1205

**Pull request merged**
