### PR TITLE
remove column stickiness

### LINKED ISSUE #503: sidebar overlaps header when navigating within a page
**What did you do?**

1. Skip filling out `Information about you` (so there are a bunch of errors)
1. Click `Review` for that section
1. Click on one of the questions.

**What did you expect to see?**

The sidebar hidden behind the heading.

**What did you see instead?**

The sidebar overlaps the heading.

screenshot

**Additional Information**

Originally reported in https://github.com/18F/e-QIP-prototype/pull/482#issuecomment-401929714, but happening on the `develop` branch. @ryanhofdotgov Mind also confirming you're seeing this on `develop`?

/cc #502

### PR DESCRIPTION
**Pull request by afeld**
Fixes #503.

The vertical stickiness behavior of the sidebar and the main content is buggy and adds a lot of complexity, and I don't actually think it improves the user experience.

**Before**

screen recording 2018-07-03 at 01 22 pm

**After**

screen recording 2018-07-03 at 01 23 pm

### CODE REVIEW

**Comment by afeld** [comment]
Hold up on merging - checking if a bug is related to this.

**Comment by ryanhofdotgov** [comment]
@bpdesigns What's your take on this change?

**Comment by afeld** [comment]
Nevermind re: the bug - not a regression.

**Comment by bpdesigns** [comment]
@afeld @ryanhofdotgov looks good to me.

**Pull request merged**
