### PR TITLE
updates to spacing

### PR DESCRIPTION
**Pull request by line47**
Giving this another go and applying an additional SCSS fix for the anchor height. https://github.com/18F/e-QIP-prototype/pull/745/files#diff-7b204005360e89eeebe91fcee793e248R18 see these 2 lines

This is part of the work related to UI improvements which include 
Fixes https://github.com/18F/e-QIP-prototype/issues/370
Fixes https://github.com/18F/e-QIP-prototype/issues/367

- Lessening the space between questions
- Updating the width of accordions to flow with the left edge of the page
- Lessening the padding around the accordion contents
- Adding a container around the save button to better control the spacing of the button at different screen resolutions
- Increasing the page width and left justifying the page content instead of centering
- Removing styles that are no longer needed (cleanup)

## Screenshots

screen shot 2018-08-21 at 4 40 34 pm
screen shot 2018-08-21 at 4 40 41 pm
screen shot 2018-08-21 at 4 41 38 pm
screen shot 2018-08-21 at 4 43 48 pm

### CODE REVIEW

**Comment by line47** [comment]
**IE 11 screenshots**
Spacing still looks just fine 👍 

ie-11
ie-11-2
ie-11-3

**Comment by line47** [comment]
**IE Edge screenshots** (has issues but none related to the spacing changes in this PR.
edge-1
edge-2
edge-3

**Comment by line47** [comment]
@ryanhofdotgov and @hursey013 - reviewed this is IE 11 and Edge and included screenshots. 
Feeling good about this work 👍

**Comment by hursey013** [comment]
@line47 I've seen that issue with SVGs appearing black (like the OPM logo in the screenshot). I documented the same thing on login.gov, let me see if I can track it down.

**Comment by hursey013** [comment]
Although as you mentioned, not tied directly to this issue, so I'll write up a separate ticket for it.

**Pull request merged**
