### PR TITLE
[WORK IN PROGRESS] generate Financial section dynamically

### PR DESCRIPTION
**Pull request by afeld**
Part of #614. Builds on #702.

### CODE REVIEW

**Comment by afeld** [comment]
This is close!

* [ ] Ensure all attributes are present (`scrollToBottom`, `AddressBooks`, `defaultstate`)
* [ ] Refactor `FinancialSections`

**Comment by el-mapache** [comment]
@hursey013 Do you have any context for this? Aiden's last point about refactoring the file is super unspecific. I'd like to close this PR if it's not something we can commit to finishing

**Comment by hursey013** [comment]
@el-mapache Aidan started with refactoring the `Identification` section to use some shared code to simplify all of the sections. This PR was meant to illustrate how to apply those changes to all of the other sections, using `Financial` as an example. Wrapping this up got deprioritized over time though, so I can't say that I'd be able to quickly wrap this up without going back and revisiting all of the other previous PRs and trying to figure out how the refactor actually works.

I guess ultimately this is a decision for @michaelccata and @ryanhofdotgov on whether this is a priority or should be tabled for now.

**Comment by ryanhofdotgov** [comment]
Let's earmark this for next sprint and discuss during next week's planning. At the conclusion of this sprint, we should have addressed all the major blockers from product owner's point of view and the code is in half-baked state until this gets wrapped up, along with the other sections.

**Comment by hursey013** [comment]
Closing this branch in favor of a new one since this branch has become out of date and merging/rebasing with `develop` causes numerous merge conflicts.

**Pull request closed without merging**
