### PR TITLE
Adds text for employment types to match e-QIP

### LINKED ISSUE #1198: Add "(excluding self-employment)'" to employment type text of non Government employment
Section: Employment Activity - Discrepancy when applicant chooses employment type: eApp shows 'Non-government employment', e-QIP shows 'Non-government employment (excluding self-employment)'.  #1015

### PR DESCRIPTION
**Pull request by christopherhuii**
Fixes #1198 

Adds the correct radio button labels for State Government and Non-government employment. Also adds styles so things are more consistent.

### CODE REVIEW

**Comment by hursey013** [comment]
In Chrome it looks like it needs some additional space between the label and the smaller text below it:
screen shot 2018-11-28 at 5 00 25 pm

**Comment by ryanhofdotgov** [comment]
@christopherhuii Would you also check IE11 and post a screenshot of that once you are satisfied with it? Thanks.

**Comment by christopherhuii** [comment]
screen shot 2018-11-28 at 2 41 26 pm

Strange, this is what it looks like in Chrome for me

And IE11:

screen shot 2018-11-28 at 2 44 29 pm

**Comment by ryanhofdotgov** [comment]
@christopherhuii Was this PR still waiting on some local commits that didn't get pushed?

**Comment by christopherhuii** [comment]
Wow, I did it again. Just pushed that commit up.

**Pull request merged**
