### PR TITLE
Test case #4

### LINKED ISSUE #724: Prepare and submit NBIB test case #4
Prepare and submit [NBIB test case #4](https://docs.google.com/document/d/17wH_EXRzrlC9KksbQlx-9uTMLjSLjSO199E7XAJh0Ho/edit#heading=h.j7v108xspr7u) and resolve any issues discovered in the process.

### PR DESCRIPTION
**Pull request by ryanhofdotgov**
Fixes #724

### CODE REVIEW

**Comment by ryanhofdotgov** [comment]
Like with #681, due to the partner agency desire to all 5 test scenarios successfully submitting into e-QIP by Friday/early next week, I've split off the automated tests for all of these changes into #732.

**Comment by hursey013** [comment]
Looks like I get a couple of failures when running xml tests with `make test` locally, but could possibly be specific to my local env?

```
--- FAIL: TestScenario1 (0.40s)
	xml_test.go:319: exec: "xmllint": executable file not found in $PATH
--- FAIL: TestScenario2 (0.78s)
	xml_test.go:319: exec: "xmllint": executable file not found in $PATH
--- FAIL: TestScenario4 (0.62s)
	xml_test.go:319: exec: "xmllint": executable file not found in $PATH
--- FAIL: TestScenario6 (0.45s)
	xml_test.go:319: exec: "xmllint": executable file not found in $PATH
```

**Comment by ryanhofdotgov** [comment]
@hursey013 I added `xmllint` to the base golang image. Can you run `make setup-containers` then re-run the test? Forgot to mention this. 

The CI always does that, but we have to remember to note to the team when we do that since we just run the individual commands for the part of the workflow we are interested in, instead of running everything from scratch each time.

**Comment by ryanhofdotgov** [comment]
Basically, every time a Docker file under `conf/docker/` changes, you have to re-run `make setup-containers`. It's a pretty rare event these days.

**Comment by hursey013** [comment]
Yeah, once I started digging and saw `libxml2-utils` getting installed I figured I was missing some dependencies. Works fine after rebuilding 👍

**Pull request merged**
