### PR TITLE
[EN-3731] Validation Refactor - Foreign / Travel

### PR DESCRIPTION
**Pull request by suzubara**
## Description

Model, tests and validator for Foreign Travel

## Checklist for Reviewer

- [ ] Review code changes
- [ ] Review changes for Database effects
- [ ] Verify change works in IE browser

More details about this can be found in [docs/review.md](docs/review.md)

### CODE REVIEW

**Comment by christopherhuii** [comment]
Looks like something might be up with this PR.

If I answer `No` to `Have you traveled outside the U.S. in the last past seven (7) years?` the section doesn't validate.

If I answer `Yes` to `Have you traveled outside the U.S. in the last past seven (7) years?` the following question appears:

```
Has your travel in the last (7) years been solely for U.S. Government business/military overseas assignment on official government orders?
```

If I answer `Yes` to that, the subsection validates and no accordions show up. If I answer `No`, the accordions show up. It looks like the logic is backwards.

**Comment by suzubara** [comment]
@christopherhuii I believe that's in line with the existing logic, i.e. it only asks you about travel if you have traveled other than trips for the U.S. gov.

**Comment by christopherhuii** [comment]
@suzubara Hm that's interesting. This subsection follows opposite logic compared to other sections, but I guess that's just how it is ¯\_(ツ)_/¯

When answering `No` to `Have you traveled outside the U.S. in the last past seven (7) years?` the subsection doesn't validate.

**Comment by suzubara** [comment]
@christopherhuii got it, that should be fixed now!

**Pull request merged**
