### PR TITLE
Remove middle name and last name initial checkbox from employment verifier

### LINKED ISSUE #1196: Section 13: Self Employment Verifer has a middle name field in eAPP but not in eQIP.
Section 13: Self Employment Verifer has a middle name field in eAPP but not in eQIP. #1015

### PR DESCRIPTION
**Pull request by christopherhuii**
Fixes #1196 and #1197 

- Removes middle name field from the user interface
- Removes the last name initial checkbox

### CODE REVIEW

**Comment by hursey013** [comment]
Looks good so far! There will also need to be some slight adjustments to the validator for when either middle name is omitted: https://github.com/18F/e-QIP-prototype/blob/develop/src/validators/name.js#L63-L84

**Comment by christopherhuii** [comment]
Not quite sure I understand. I'm not sure how middle name validator is implemented (naming is a little confused), but `this.noMiddleName` is always false so it never enters the switch statement, It always returns `true` with no errors.

**Comment by ryanhofdotgov** [comment]
@christopherhuii #1197 isn't limited to employment verifier, it's anywhere last name appears in eApp. You can check on the SF-86 and in the validation matrix/XSD, there isn't a last name initial only attribute like with middle name (e.g, `<Middle Type=IO>`). So lets just remove the last name initial only option entirely. 

Admittedly, the description on #1197 isn't written well – they were bulk imported by Mary from an NBIB spreadsheet. I have a task this week to go through all these bulk imported NBIB tickets and expand/clarify, so hopefully shouldn't be a problem going forward.

**Comment by christopherhuii** [comment]
@ryanhofdotgov ohhhh, thanks for pointing that out. i only checked the employment verifier and didn't realize it was application wide. i undid those changes and defer the last name initial questions to #1197.

**Comment by hursey013** [comment]
@christopherhuii validator update looks good, thank you.

**Pull request merged**
