### PR TITLE
Fix label overlap for DSN phone numbers

### LINKED ISSUE #457: DSN phone number text placement overlap issue
**What did you do?**

viewed any screen with a phone number input and selected "Switch to: DSN number"

**What did you expect to see?**

I expected to see the "DSN number" header above the input fields

**What did you see instead?**

text overalp
screen shot 2018-06-20 at 11 15 40 am

**Additional Information**

This is an issue when the screen width is small

- What browser and version are you using?
 - chome
 - IE 11

- What operating system?
 - Mac
 - Windows

This is related to #224

### PR DESCRIPTION
**Pull request by christopherhuii**
Fixes #457 

The DSN label was overlapping the phone number fields because there's a negative `margin-bottom` that accounts for the "Extension" label that the Domestic and International phone numbers have.

I stuck with the original implementation and just applied the CSS rule to the labels that needed it.

### CODE REVIEW

**Comment by hursey013** [comment]
Tested this in Chrome and it looks good. It does look like there is a related (pre-existing) issue in IE11 caused by the negative margin. Do you think it makes sense to address that as part of this, or would you prefer me to make a new issue?

IE11:
screen shot 2018-10-15 at 11 53 53 am
screen shot 2018-10-15 at 11 54 08 am
screen shot 2018-10-15 at 11 54 20 am

**Comment by christopherhuii** [comment]
@hursey013 Oh that's not good. I'll take a look and address it with this issue.

**Comment by ryanhofdotgov** [comment]
Just going to add WIP in progress to PR title – just remove it when it is ready to go again.

**Comment by christopherhuii** [comment]
@ryanhofdotgov @hursey013 Fixed IE11 issues and a snapshot test

screen shot 2018-10-17 at 11 53 27 am
screen shot 2018-10-17 at 11 53 44 am

**Comment by hursey013** [comment]
Checked on IE, looks great, nice work. Not sure what's going on with the snapshot, how are you updating them?

**Comment by christopherhuii** [comment]
In all honesty, I'm not too sure. I don't think my changes affects the snapshot tests, but I decided to update the tests with this PR.

I did `yarn test -u` to update the snapshots. Although looking at it now, it doesn't like the CircleCI is happy with it.

**Comment by ryanhofdotgov** [comment]
Since the snapshot generation is the one? thing we do outside the configuration-managed containers, is it possible there's a version mismatch?

**Comment by hursey013** [comment]
@christopherhuii for now I would just remove the offending snapshot file from your PR (since as you mentioned, your changes do not impact the navigation) so we can get this merged in and then we can sort out the snapshot stuff separately.

**Comment by christopherhuii** [comment]
@hursey013 I removed the commit  and force pushed. Since itis my own branch, I thought it'd be okay. Looks like the tests are passing now.

**Pull request merged**
