### PR TITLE
Update Mux to restore status code fix

### PR DESCRIPTION
**Pull request by macrael**
The old version of Mux we were using had a bug when interacting with the standard context package, the fix to implement status codes used that package and so was reverted. This un-reverts those changes and updates mux so there is not a conflict anymore. 

I've tested this locally with CORS enabled. There was a problem before where updating Mux broke CORS OPTION requests, but that does not appear to be a problem anymore. It's probably worth testing this in a staging environment incase something is different from the local environment.

### CODE REVIEW

**Comment by ryanhofdotgov** [comment]
@macrael In absence of something automated, have you done a (manual) full end-to-end process test with these changes? For example, some thing like:
* purge database
* load up test scenario
* change some data, save
* log out, log in
* click through section reviews
* go to final review, sign all the waivers
* submit application
* download all the digitally signed PDF waivers/releases

**Comment by macrael** [comment]
I did the above locally and everything seemed to work fine.

**Comment by macrael** [comment]
@ryanhofdotgov unless you think we should try and push this to the staging area for a final test I think that this looks like its working as is.

**Comment by ryanhofdotgov** [comment]
Fixes #1101

**Pull request merged**
