### PR TITLE
[WIP] Adding Certificate of Citizenship as a document type

### LINKED ISSUE #1568: Change branching for document of U.S. Citizen born abroad in Citizenship status section
**Adding Certificate of citizenship as a document type**
Given I am on the Citizenship status subection
When I choose `I am a U.S. citizen or national by birth, born to U.S. parent(s), in a foreign country`
Then I should see a question asking me to `Provide type of documentation of U.S. citizen born abroad`
And the choices should be: FS-240, DS-1350, FS-545, Certificate of citizenship, and Other
**This has been broken out into #1578** 

**Choosing FS-240, DS-1350, FS-545, or Other**
Given I have chosen `I am a U.S. citizen or national by birth, born to U.S. parent(s), in a foreign country`
When I choose `FS-240, DS-1350, FS-545, or Other`
Then I should see fields for: document number, date issued, place of issuance, name document was issued, born on military installation
And If I have chosen `Other` I should see an explanation field before all the above fields
**This has been broken out into #1579**

**Choosing Certificate of citizenship**
Given I have chosen `I am a U.S. citizen or national by birth, born to U.S. parent(s), in a foreign country`
When I choose `Certificate of citizenship`
Then I should see fields for: Certificate number, date issued, name document was issued, born on military installation
**This has been broken out into #1580** 

#1327 **MUST** be closed before👇🏼can be completed
**Having a valid U.S. passport**
Given I have provided a valid U.S. passport in the previous section
When I choose `I am a U.S. citizen or national by birth, born to U.S. parent(s), in a foreign country`
Then I should **NOT** see the `Provide type of documentation of U.S. citizen born abroad` question
And I should only have to answer if I was born on a military installation

### LINKED ISSUE #1578: Add Certificate of citizenship as a document type
This is part 1 of 4 towards updating the branching for document of U.S. Citizen born abroad in Citizenship status section.

Given I am on the Citizenship status subection
When I choose `I am a U.S. citizen or national by birth, born to U.S. parent(s), in a foreign country`
Then I should see a question asking me to Provide type of documentation of U.S. citizen born abroad
And the choices should be: `FS-240`, `DS-1350`, `FS-545`, `Certificate of Citizenship`, and `Other`

### LINKED ISSUE #1579: Updating branching when FS-240, DS-1350, FS-545, or Other are selected
This is part 2 of 4 towards updating the branching for document of U.S. Citizen born abroad in Citizenship status section.

Given I have chosen `I am a U.S. citizen or national by birth, born to U.S. parent(s), in a foreign country`
When I choose `FS-240`, `DS-1350`, `FS-545`, or `Other`
Then I should see fields for: document number, date issued, place of issuance, name document was issued, born on military installation
And If I have chosen `Other` I should see an explanation field before all the above fields

### LINKED ISSUE #1580: Update branching when "Certificate of Citizenship" is selected
This is part 3 of 4 towards updating the branching for document of U.S. Citizen born abroad in Citizenship status section.

Choosing Certificate of citizenship
Given I have chosen `I am a U.S. citizen or national by birth, born to U.S. parent(s), in a foreign country`
When I choose `Certificate of citizenship`
Then I should see fields for: Certificate number, date issued, name document was issued, born on military installation

### PR DESCRIPTION
**Pull request by christopherhuii**
## Description
Fixes #1578 
Fixes #1579 
Fixes #1580
Fixes #1568 

#1568 was broken out into individual issues, but since they were all relatively low effort and related, I bundled them all back together.

Because `Certificate of Citizenship` isn't a valid option in eQIP, when a user selects `Certificate of Citizenship` as their document type, it populates `AbroadDocumentation` as `Other` and `Explanation` as `Certificate of Citizenship
## Checklist for Reviewer

- [ ] Review code changes
- [ ] Review changes for Database effects
- [ ] Verify change works in IE browser

More details about this can be found in [docs/review.md](docs/review.md)

### CODE REVIEW

**Comment by christopherhuii** [comment]
@michaelccata @ryanhofdotgov I'm not sure who was in the meeting when #1568 was created, but the issue details don't mention what the `value` submitted to eQIP/IM should be for this document type. I just made it `CertificateOfCitizenship` ¯\_(ツ)_/¯

**Comment by ryanhofdotgov** [comment]
@christopherhuii To find what should be submitted to e-QIP, you need to pull up the validation matrix for this question and cross check it with the applicant XSD.

**Comment by christopherhuii** [comment]
That's kinda where my confusion lies. In the validation matrix, `Certificate of Citizenship` isn't listed.

Screen Shot 2019-03-25 at 7 43 58 AM

**Comment by ryanhofdotgov** [comment]
@christopherhuii 
1) If there isn't an option in e-QIP, then we can't accept it for the 86 – I was trying to avoid getting read in on the whole issue, but I'll look at this more closely now.

2) That type of discrepancy is a blocking/high priority type of issue, since it means an e-QIP submit would fail (i.e., wouldn't validate). That's being tracked https://github.com/18F/e-QIP-prototype/issues/1514 and will be resolved today or tomorrow.

**Comment by ryanhofdotgov** [comment]
@christopherhuii This is being solved a different way via https://github.com/18F/e-QIP-prototype/pull/1653 and can be closed now right?

**Comment by christopherhuii** [comment]
They're slightly different, but we can close this out. We're handcuffed a bit on this one since it differs from OPM/e-QIP

**Pull request closed without merging**
