### PR TITLE
Run strict eslint rules against changed files in commit

### PR DESCRIPTION
**Pull request by gidjin**
## Description

Run airbnb lint rules against changes in a commit to help us improve the code as we work

## Checklist for Reveiwer

- [ ] Review code changes
- [ ] Review changes for Database effects
- [ ] Verify change works in IE browser

More details about this can be found in [docs/review.md](docs/review.md)

### CODE REVIEW

**Comment by christopherhuii** [comment]
Do you have ESLint listening to changes as you type? I'm struggling to get it to run in my text editor (VS Code).

I'm happy to configure this for my text editor if you have it working for yours.

**Comment by gidjin** [comment]
To avoid failing the build I created a new ESLint rc file `.eslintrc.dev.yml` I would expect you would need to point your editor to that rc file to get the updated rules. I do have the lint rules running in nvim but I have not changed it to use the new rc file.

**Comment by suzubara** [comment]
To use in VSCode, add the following to your `settings.json` file:
```
"eslint.options": {
  "configFile": ".eslintrc.dev.yml"
}
```

**Comment by gidjin** [comment]
That was not intended behavior, I've corrected the script to require both ESLint and lint-css to pass. Let me know if it does not work for you.

**Pull request merged**
