### PR TITLE
Do not auto fill in gap dates as they may be confusing

### PR DESCRIPTION
**Pull request by gidjin**
Github Issue #1174

### CODE REVIEW

**Comment by gidjin** [comment]
Yeah I saw that. The section is automatically sorted by date. The error doesn't disappear also because the new section doesn't have a date, since the user technically still has a gap. I wonder if scrolling to the new section is enough to resolve that. Though the validation isn't rerun when you edit the new section so it doesn't go away until you go to the next section. Another option is to fill in one of the dates, like the from. I haven't tried that though to see if it resolves the error, but I image it would allow us to sort it.

@joshmfranklin any thoughts on what would be better from a user perspective?

**Comment by joshmfranklin** [comment]
@gidjin here are the two things we discussed during our chat: 

Option 1: See if adding the `from date` helps with placing the new accordion in the right spot when clicking on the "Add new employer" button in a gap validation error

Option 2: Always place the gap validation error at the end of the accordion list and replace it with a new accordion when clicking on the "Add new employer" button.

**Comment by gidjin** [comment]
I updated the pr to support having blank dates, but now the gap error is removed when you click to add a new range, and the new range & the gap will appear at the bottom of the list. Hopefully this helps with the usability.

**Comment by christopherhuii** [comment]
I'm not sure if this is intentional or not, but I found some behavior I think is strange. This might just result in a separate GitHub issue.

screen shot 2018-12-18 at 7 56 24 am
In the image above, I have a gap in my employment, which is expected.

If I save and revisit the section, eApp will save that gap employment entry.
screen shot 2018-12-18 at 7 59 49 am

As a user, I'd expect to still see the gap entry instead of eApp automatically creating an employment item with the gap dates.

**Comment by hursey013** [comment]
I'm seeing something similar to @christopherhuii, and agree that it might be a separate issue. If I'm working on the employment section for example, enter in several entires, then navigate away, and then return I see the gap warning at the bottom of the accordion (with blank dates) as expected. However if I log out and back in, return to employment, I see an entry with exact dates autopopulated in the the gap, as well as the blank entry (without dates) at the bottom of the list.

**Comment by gidjin** [comment]
I was discussing this with Chris and we both see the issue described on develop as well as on my branch so it seems not related to my changes since it's a pre-existing issue. He was going to file a bug issue for it since it's not caused by these changes.

**Comment by hursey013** [comment]
New issue relating to sorting residences chronologically: https://github.com/18F/e-QIP-prototype/issues/1281 - which is relevant now that the gap warning message will be displayed at the bottom of the list.

**Pull request merged**
