### PR TITLE
Dynamic Section Generator

### PR DESCRIPTION
**Pull request by christopherhuii**
@christopherhuii accidentally merged the this branch before the issue was complete. He merged the "Financial" section on accident because it was the only one that was complete at the moment. Wait until remaining sections are complete.

* [ ] Relationships
* [x] Citizenship
* [ ] Military
* [ ] History
* [ ] Foreign
* [ ] Legal
* [ ] Psychological
* [ ] SubstanceUse

### CODE REVIEW

**Comment by hursey013** [comment]
Mind taking a look @christopherhui (wouldn't let me tag you as a reviewer since you opened the PR)

**Comment by christopherhui** [comment]
Hey you tagged the wrong person! 😅

**Comment by gidjin** [comment]
@christopherhuii Please see Brian's comment. I was wondering why you had to i's in your username.

**Comment by hursey013** [comment]
> Hey you tagged the wrong person! 😅

Sorry for the confusion @christopherhui!

**Comment by christopherhuii** [comment]
looks good to me. manually filled out the form and loaded up test case 7 and things are functioning and filling out properly in the Citizenship section.

**Pull request merged**
