### PR TITLE
[EN-3795] Fixes the filling out of mandatory counseling and navigation to voluntary subsection

### PR DESCRIPTION
**Pull request by christopherhuii**
## Description
This PR fixes two issues that come from a single root cause.

- `Have any of the following ordered, advised, or asked you to seek counseling or treatment as a result of your illegal use of drugs or controlled substances?` does not save.
- Cannot navigate to the next section

It's not exactly clear how or when this bug was introduced, but the issue in the code has to do with the variable type. The function was expecting an object, but it was being passed an array. This issue is similar to the `values`, but that seems to occasionally reoccur. I've updated that component function and a number of tests to make sure this doesn't happen again.

## Checklist for Reviewer

- [ ] Review code changes
- [ ] Review changes for Database effects
- [ ] Verify change works in IE browser

More details about this can be found in [docs/review.md](docs/review.md)

### CODE REVIEW

**Comment by ryanhofdotgov** [comment]
@christopherhuii Can you clarify what you mean by "This issue is similar to the values, but that seems to occasionally reoccur"?

**Comment by joshmfranklin** [comment]
@christopherhuii not sure if this has something to do with my setup or the changes made, but when i clear my db and then reload the app but the first question in `Mandatory counseling or treatment` is always answered `no` by default.

**Comment by joshmfranklin** [comment]
@christopherhuii I'm not sure if this is a problem with my setup or something to do with the changes for this issue, but after I clear my db locally the first question in `Mandatory counseling or treatment` is always answered `no` and there are questions answered in `Voluntary counseling or treatment` as well.

**Comment by christopherhuii** [comment]
@ryanhofdotgov A similar example is countries. The value (as in key value pair) can be a string or an object.

Example:
```
// string
country: 'United Status'

// object
country: {
  value: 'United States',
}
```

This had been a problem in the past.

In this situation, `this.props.OrderedBy` is expected to be an object with the `values` key. For some reason, it was just the value.

@joshmfranklin I'm not seeing that issue on my end. Maybe I can take a look at what you're seeing later.

**Pull request merged**
