### PR TITLE
[WIP] Failure spec for identification using cypress.io

### LINKED ISSUE #1274: Add basic failure path test for identification section
Currently the feature specs provide minimal test coverage. For this task please add a basic failure path test for the identification section. Something like going straight to the review and seeing that all the errors show up and then filling in the fields or something.

Reference: https://docs.google.com/document/d/1HoXI8i4wBcjWq_elD39BuNYdesi8cjHnnERLk4JcfT4/edit#bookmark=id.yw3fljo9pvsh

See #1212 as it implemented the minimal happy path check

### PR DESCRIPTION
**Pull request by gidjin**
Fixes #1274 by adding a test for failures that can be seen on the identification section review. The failures in each question were intermittently showing up so I decided to leave those tests for until the intermittent issues with validations are looked into. This test also uses cypress.io as it adds many advantages over Nightwatch.js. 

- Cypress.io has a GUI where the developer can watch the test run and step back to any previous point for debugging
- Cypress.io has docker images pre-made allowing us to continue using docker containers for running tests
- Cypress.io takes video of test runs so developer can watch the test session. Videos are generated even when run in a docker container
- Cypress.io makes it simpler for finding and testing various aspects of the UI over Nightwatch.js

### CODE REVIEW

**Comment by macrael** [comment]
Still need to solve one more snyk issue

**Comment by macrael** [comment]
still LGTM

**Comment by gidjin** [comment]
Discussed with Ryan, and we don't feel this is the right choice going forward for this project. I will be writing up our decision soon.

**Comment by gidjin** [comment]
Closing this as we are not implementing cypress for eApp at this time.

**Pull request closed without merging**
