### PR TITLE
Clean up of e-QIP submit tool, add documentation

### PR DESCRIPTION
**Pull request by ryanhofdotgov**
Addresses #1207

### CODE REVIEW

**Comment by ryanhofdotgov** [comment]
@macrael When you review this PR, would you go through all the steps to validate the XML via xmllint and to submit a scenario to e-QIP? Hoping you will identify any gaps in my instructions. Thanks!

**Comment by ryanhofdotgov** [comment]
When you get to the step where you need WS_KEY, contact me instead of what the linked documentation indicates. That's the only process step in flux.

**Comment by macrael** [comment]
`$ ./submit complete-scenarios/test3.json
submit: import into e-QIP successful: agencyKey=**, requestKey=**`

The tool and the instructions work. I would just add a line about the test needing to be on an approved network to the instructions. I went to the confluence page just looking for the values for the WS variables, not info about the submission process.

**Comment by ryanhofdotgov** [comment]
The text above the URL to the not-for-public-release portion of the instructions currently says "For appropriate values for the other configuration settings plus network requirements:", but I'll add some clarifying text.

**Comment by ryanhofdotgov** [comment]
In addition to the tweaking the public text, I linked to the appropriate anchor in the private documentation page, and visually emphasized network requirements in an info-style callout box there.

**Pull request merged**
