### PR TITLE
SF-85 logic (sections 6-10)

### LINKED ISSUE #1543: Form type changes (Sections 6-10)
Address changes required for different form types in sections: Foreign associations, Financial record, Substance use, Investigative and criminal history, Psychological and emotional health.

Includes hiding questions, hiding subsections, hiding sections, language/parameter changes.

Depends on the above sections' render refactoring being completed.

### PR DESCRIPTION
**Pull request by suzubara**
## Description

- Fixes #1543 
- Abstract out function for determining what is required by given form types
- Make SF-85 logic & content changes for sections 6-10
  - Change time frame for questions in `Financial / Delinquent, Financial / Taxes, Legal / Investigations / Debarred, Legal / Investigations / Revoked, Legal / Police / Offenses, SubstanceUse / Drugs / DrugInvolvements, SubstanceUse / Drugs / DrugUses, SubstanceUse / Drugs / OrderedTreatments, SubstanceUse / Drugs / PrescriptionUse, SubstanceUse / Drugs / VoluntaryTreatments`
  - Hide questions from `Legal / Police / Offenses` about involvements and sentencing/incarceration
  - Hide questions from `Substance Use / Drugs / DrugUses, Substance Use / Drugs / DrugInvolvements, SubstanceUse / Drugs / PrescriptionUses` about drug use/involvement while employed, with security clearance, and intent in the future
- Hide subsections from SF-85, including from each sections' Review screen
- Refactored validators that required adding conditional validation based on form type
- Stubbed out new `ClearanceGranted` question logic (this will be completed in another branch)
- Lint fixes

## Checklist for Reviewer

- [ ] Verify that going through the SF-85 shows the correct sections and questions based on the content guide
- [ ] Verify that in the 85, adding a Financial Delinquent item saves the `Infractions` value as "Federal" automatically
- [ ] Review code changes
- [ ] Review changes for Database effects
- [ ] Verify change works in IE browser

More details about this can be found in [docs/review.md](docs/review.md)

### CODE REVIEW

**Comment by joshmfranklin** [comment]
Looks great! only one comment: 

- [ ] *Investigative and criminal history / Association record / Terrorist organization:* Remove the word `security` from the first sentence

**Comment by suzubara** [comment]
@joshmfranklin Okay that should be taken care of now!

**Comment by christopherhuii** [comment]
I believe the result of this PR should make the form submittable because all the form/question changes have been taken care of. Please let me know if that's not a true statement. 

I'm struggling get `Where you have lived` or `Employment activities` to validate on the SF85.

**Comment by suzubara** [comment]
@christopherhuii I don't think issues relating to `Your History` will be impacted by this PR, but I also wasn't able to reproduce (filling out an 85 from scratch I was able to submit it successfully). Does the same issue happen on `develop` and/or can you provide more information? It might be something we have to create a new issue for.

**Comment by suzubara** [comment]
@joshmfranklin Thanks! That should be fixed now

**Pull request merged**
